language: ruby
rvm:
  - 2.1.1
  - 1.9.3
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
