source "https://api.berkshelf.com"

group :integration do
  cookbook 'minitest-handler'
end


cookbook 'chruby'
cookbook 'nginx'
cookbook 'postgresql'
cookbook 'database'
cookbook 'unicorn'
cookbook 'runit'
cookbook 'yum-epel'
cookbook 'yum-gina', git: 'git@github.com:gina-alaska/yum-gina-cookbook'
cookbook 'redisio', '~> 1.7.0'
cookbook 'magic_shell'
cookbook 'gina-gluster', git: 'git@github.com:gina-alaska/gina-gluster-cookbook'
metadata
