# -*- mode: ruby -*-
# vi: set ft=ruby :

DEVVM_IP = '192.168.0.57'

Vagrant.configure("2") do |config|
  config.vm.hostname = "feeder-web-development"

  config.vm.box = "opscode_centos-6.4_provisionerless"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box"

  config.vm.network :private_network, ip: DEVVM_IP

  config.vm.synced_folder "../", "/www/feeder-web/current"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest

  #Force ip4/6 requests to be made seperatly
  config.vm.provision :shell, inline: "if [ ! $(grep single-request-reopen /etc/sysconfig/network) ]; then echo RES_OPTIONS=single-request-reopen >> /etc/sysconfig/network && service network restart; fi"

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      'chruby' => {
        'default' => 'embedded'
      },
      "feeder-web" => {
        'account' => "vagrant",
        'environment' => "development",
        'databases' => {
          'development' => {
            'hostname' => DEVVM_IP,
            'password' => 'feeder-web_dev_postgres',
          },
          'test' => {
            'hostname' => DEVVM_IP,
            'database' => 'feeder-web_test',
            'username' => 'feeder-web_test',
            'password' => 'feeder-web_test_postgres',
            'search_path' => 'feederweb_test,public',
            'adapter' => 'postgresql'
          }
        },
        'paths' => {
          'shared' => "/www/feeder-web/current",
          'config' => "/www/feeder-web/current/config",
          'initializers' => "/www/feeder-web/current/config/initializers",
          'archive' => "/www/feeder-web/current/archive",
          'uploads' => "/www/feeder-web/current/uploads",
          'cms' => "www/feeder-web/current/public/cms",
          'repos' => "www/feeder-web/current/repos"
        },
        'unicorn' => {
          'listen' => '/var/run/unicorn/',
          'pid' => '/www/feeder-web/current/tmp/pids/unicorn_feeder-web.pid',
          'stderr_path' => '/www/feeder-web/current/log/unicorn.stderr.log',
          'stdout_path' => '/www/feeder-web/current/log/unicorn.stdout.log'
        },
        'database_setup' => true,
        'ruby_version' => '1.9.3'
      },
      'postgresql' => {
        'password' => {
          'postgres' => "fasdfasdfasdfasdf"
        },
        'config' => {
          'listen_addresses' => '*'
        }
      }
    }

    chef.run_list = [
      "recipe[feeder-web::default]"
    ]
  end
  config.vm.provision :shell, inline: <<-EOF
echo "******************************************************************"
echo "*                                                                *"
echo "*  Your development environment is available at #{DEVVM_IP.ljust(15)}  *"
echo "*                                                                *"
echo "******************************************************************"
  EOF
end
